import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# ============================================================
# Evolution model (cost function comparison)
# Goal: test whether delta* stays in the criterion window
# under DIFFERENT cost functions.
#
# If delta* stays in window under both quadratic AND exponential
# cost, the "Red Queen maintains high mortality" claim is robust.
# If it only works for quadratic, the claim is an artifact of
# the cost function choice.
# ============================================================

r0 = 0.7
delta0 = 0.1
beta_max = 1.5
b_cost = 0.3
v_H = 0.1
v_V = 0.1
K_N = 50.0
K_V = 10.0
delta_lower, delta_upper = 0.177, 0.346


def run_evolution(cost_type='quadratic', c_cost=0.5, alpha_max=0.9, T=400):
    def evolution(t, state):
            x, y, N, V = state
                    if cost_type == 'quadratic':
                                dcost_dx = 2 * c_cost * x
                                            cost = c_cost * x**2
                                                    else:  # exponential
                                                                dcost_dx = c_cost * np.exp(x)
                                                                            cost = c_cost * (np.exp(x) - 1)

                                                                                    dw_H_dx = -dcost_dx + alpha_max
                                                                                            dw_V_dy = beta_max * N / (K_N + N) - 2 * b_cost * y
                                                                                                    dxdt = v_H * dw_H_dx
                                                                                                            dydt = v_V * dw_V_dy
                                                                                                                    r = r0 - cost
                                                                                                                            delta = delta0 + beta_max * y - alpha_max * x
                                                                                                                                    dNdt = N * (r - delta) * (1 - N / K_N)
                                                                                                                                            dVdt = V * (beta_max * y * N / (K_N + N)
                                                                                                                                                                - b_cost * y**2) * (1 - V / K_V)
                                                                                                                                                                        return [dxdt, dydt, dNdt, dVdt]

                                                                                                                                                                            sol = solve_ivp(evolution, (0, T), [0.1, 0.1, 10.0, 1.0],
                                                                                                                                                                                                t_eval=np.linspace(0, T, 4000), method='LSODA')
                                                                                                                                                                                                    delta_t = delta0 + beta_max * sol.y[1] - alpha_max * sol.y[0]
                                                                                                                                                                                                        return sol.t, delta_t, sol.y[0], sol.y[1]


                                                                                                                                                                                                        # ============================================================
                                                                                                                                                                                                        # Single-run comparison
                                                                                                                                                                                                        # ============================================================
                                                                                                                                                                                                        t_quad, delta_quad, x_quad, y_quad = run_evolution('quadratic')
                                                                                                                                                                                                        t_exp, delta_exp, x_exp, y_exp = run_evolution('exponential')

                                                                                                                                                                                                        delta_quad_final = delta_quad[-1]
                                                                                                                                                                                                        delta_exp_final = delta_exp[-1]

                                                                                                                                                                                                        print(f"Quadratic cost: δ* = {delta_quad_final:.4f}")
                                                                                                                                                                                                        print(f"Exponential cost: δ* = {delta_exp_final:.4f}")
                                                                                                                                                                                                        print(f"Window: [{delta_lower}, {delta_upper}]")
                                                                                                                                                                                                        print(f"Quadratic inside window: "
                                                                                                                                                                                                              f"{delta_lower <= delta_quad_final <= delta_upper}")
                                                                                                                                                                                                              print(f"Exponential inside window: "
                                                                                                                                                                                                                    f"{delta_lower <= delta_exp_final <= delta_upper}")


                                                                                                                                                                                                                    # ============================================================
                                                                                                                                                                                                                    # Parameter space for both cost functions
                                                                                                                                                                                                                    # ============================================================
                                                                                                                                                                                                                    r0_vals = [0.6, 0.7, 0.8]
                                                                                                                                                                                                                    alpha_vals = [0.8, 0.9, 1.0]
                                                                                                                                                                                                                    c_vals = [0.4, 0.5, 0.6]

                                                                                                                                                                                                                    results_quad = np.zeros((len(r0_vals), len(alpha_vals), len(c_vals)))
                                                                                                                                                                                                                    results_exp = np.zeros_like(results_quad)

                                                                                                                                                                                                                    for i, r0v in enumerate(r0_vals):
                                                                                                                                                                                                                        for j, av in enumerate(alpha_vals):
                                                                                                                                                                                                                                for k, cv in enumerate(c_vals):
                                                                                                                                                                                                                                            globals()['r0'] = r0v
                                                                                                                                                                                                                                                        _, dq, _, _ = run_evolution('quadratic',
                                                                                                                                                                                                                                                                                                 c_cost=cv, alpha_max=av, T=300)
                                                                                                                                                                                                                                                                                                             results_quad[i, j, k] = dq[-1]
                                                                                                                                                                                                                                                                                                                         _, de, _, _ = run_evolution('exponential',
                                                                                                                                                                                                                                                                                                                                                                  c_cost=cv, alpha_max=av, T=300)
                                                                                                                                                                                                                                                                                                                                                                              results_exp[i, j, k] = de[-1]

                                                                                                                                                                                                                                                                                                                                                                              n_in_quad = np.sum((results_quad >= delta_lower)
                                                                                                                                                                                                                                                                                                                                                                                                 & (results_quad <= delta_upper))
                                                                                                                                                                                                                                                                                                                                                                                                 n_in_exp = np.sum((results_exp >= delta_lower)
                                                                                                                                                                                                                                                                                                                                                                                                                   & (results_exp <= delta_upper))


                                                                                                                                                                                                                                                                                                                                                                                                                   # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                   # Plot
                                                                                                                                                                                                                                                                                                                                                                                                                   # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                   fig, axes = plt.subplots(1, 3, figsize=(18, 5))

                                                                                                                                                                                                                                                                                                                                                                                                                   # Panel A: time series comparison
                                                                                                                                                                                                                                                                                                                                                                                                                   axes[0].plot(t_quad, delta_quad, 'b-', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                label=f'Quadratic, δ*={delta_quad_final:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].plot(t_exp, delta_exp, 'r--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                             label=f'Exponential, δ*={delta_exp_final:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].axhspan(delta_lower, delta_upper, alpha=0.2, color='green',
                                                                                                                                                                                                                                                                                                                                                                                                                                                             label=f'Window [{delta_lower}, {delta_upper}]')
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].set_xlabel('Time')
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].set_ylabel('Mortality δ(t) (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].set_title('A. Evolution dynamics')
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].legend(fontsize=8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                             # Panel B: parameter space comparison
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[1].scatter(results_quad.flatten(), results_exp.flatten(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             s=80, alpha=0.7, c='purple', edgecolor='k')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[1].plot([delta_lower, delta_upper], [delta_lower, delta_upper],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'k--', linewidth=1, alpha=0.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].axvspan(delta_lower, delta_upper, alpha=0.15, color='green')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].axhspan(delta_lower, delta_upper, alpha=0.15, color='green')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].set_xlabel('δ* (quadratic cost)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].set_ylabel('δ* (exponential cost)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].set_title(f'B. Parameter space '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f'({n_in_quad}/27 quad, {n_in_exp}/27 exp)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Panel C: host resistance and viral infectivity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].plot(t_quad, x_quad, 'b-', linewidth=2, label='Host resistance x')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].plot(t_quad, y_quad, 'r-', linewidth=2, label='Viral infectivity y')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].set_xlabel('Time')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].set_ylabel('Trait value')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].set_title('C. Trait dynamics (quadratic)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            axes[2].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plt.savefig('evolution_model_optimized.png', dpi=150)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plt.close()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Summary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n" + "=" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Evolution model summary")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("=" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Quadratic cost: δ* = {delta_quad_final:.4f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  f"{'INSIDE' if delta_lower <= delta_quad_final <= delta_upper else 'OUTSIDE'}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print(f"Exponential cost: δ* = {delta_exp_final:.4f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"{'INSIDE' if delta_lower <= delta_exp_final <= delta_upper else 'OUTSIDE'}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Parameter space: {n_in_quad}/27 (quad), "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              f"{n_in_exp}/27 (exp)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print(f"\nInterpretation:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if n_in_quad > 15 and n_in_exp > 15:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print(" Both cost functions keep δ* in window in majority of")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print(" parameter space -> Red Queen claim is robust.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      elif n_in_quad > 15 and n_in_exp <= 15:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print(" Only quadratic cost keeps δ* in window -> Red Queen")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print(" claim is an artifact of cost function choice.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print(" Neither cost function robustly keeps δ* in window.")