import numpy as np
from scipy.integrate import solve_ivp
from scipy.stats import spearmanr
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

S = 30
m = 3
np.random.seed(42)

r = np.random.lognormal(np.log(0.7), 0.4, S)
K = np.random.lognormal(np.log(1.5), 0.4, (m, S))
V = np.random.lognormal(np.log(0.1), 0.2, (m, S))
mu = np.random.uniform(0.2, 0.4, (m, S))
S_input = np.array([0.05, 0.01, 0.003])
lambda_j = np.array([0.01, 0.01, 0.008])
alpha = 0.001


def make_model(delta_i, removed_idx=None):
    def model(t, y):
            R = y[:m]
                    N = y[m:m + S].copy()
                            if removed_idx is not None:
                                        N[removed_idx] = 0.0
                                                f = np.prod(R[:, None] / (K + R[:, None]), axis=0)
                                                        g = r * f
                                                                recycle = mu @ (delta_i * N)
                                                                        dR = S_input + recycle - V @ (f * N) - lambda_j * R
                                                                                dN = N * (g - delta_i) - alpha * N**2
                                                                                        if removed_idx is not None:
                                                                                                    dN[removed_idx] = 0.0
                                                                                                            return np.concatenate([dR, dN])
                                                                                                                return model


                                                                                                                def integrate_to_eq(model, y0, T=800):
                                                                                                                    sol = solve_ivp(model, [0, T], y0, method='LSODA',
                                                                                                                                        rtol=1e-6, atol=1e-9, max_step=5.0)
                                                                                                                                            return sol.y[:, -1]


                                                                                                                                            def numerical_jacobian(model, y, eps=1e-6):
                                                                                                                                                n = len(y)
                                                                                                                                                    J = np.zeros((n, n))
                                                                                                                                                        F0 = model(0, y)
                                                                                                                                                            for i in range(n):
                                                                                                                                                                    yp = y.copy()
                                                                                                                                                                            yp[i] += eps
                                                                                                                                                                                    J[:, i] = (model(0, yp) - F0) / eps
                                                                                                                                                                                        return J


                                                                                                                                                                                        delta_values = np.linspace(0.08, 0.35, 10)
                                                                                                                                                                                        Gammas, dispersals, deltas_used = [], [], []
                                                                                                                                                                                        gamma_net, gamma_fro = [], []

                                                                                                                                                                                        for k, delta_mean in enumerate(delta_values):
                                                                                                                                                                                            np.random.seed(42)
                                                                                                                                                                                                delta_i = np.random.lognormal(np.log(delta_mean), 0.15, S)
                                                                                                                                                                                                    model = make_model(delta_i)
                                                                                                                                                                                                        y0 = np.concatenate([np.array([5.0, 0.5, 0.3]),
                                                                                                                                                                                                                                 np.random.uniform(0.01, 0.5, S)])
                                                                                                                                                                                                                                     y_eq = integrate_to_eq(model, y0)
                                                                                                                                                                                                                                         N_eq = y_eq[m:m + S]
                                                                                                                                                                                                                                             alive = np.where(N_eq > 1e-4)[0]
                                                                                                                                                                                                                                                 if len(alive) < 5:
                                                                                                                                                                                                                                                         continue
                                                                                                                                                                                                                                                             deltas_used.append(delta_mean)

                                                                                                                                                                                                                                                                 J = numerical_jacobian(model, y_eq)
                                                                                                                                                                                                                                                                     J_RR = J[:m, :m]
                                                                                                                                                                                                                                                                         J_RN = J[:m, m:]
                                                                                                                                                                                                                                                                             J_NR = J[m:, :m]
                                                                                                                                                                                                                                                                                 J_NN = J[m:m + S, m:m + S]
                                                                                                                                                                                                                                                                                     J_eff = J_NN - J_NR @ np.linalg.solve(J_RR, J_RN)
                                                                                                                                                                                                                                                                                         Je_alive = J_eff[np.ix_(alive, alive)]

                                                                                                                                                                                                                                                                                             off_raw = Je_alive.copy()
                                                                                                                                                                                                                                                                                                 np.fill_diagonal(off_raw, 0)
                                                                                                                                                                                                                                                                                                     diag_raw = np.diag(np.diag(Je_alive))
                                                                                                                                                                                                                                                                                                         gamma = np.linalg.norm(off_raw, 'fro') / (
                                                                                                                                                                                                                                                                                                                 np.linalg.norm(diag_raw, 'fro') + 1e-10)
                                                                                                                                                                                                                                                                                                                     Gammas.append(gamma)

                                                                                                                                                                                                                                                                                                                         N_alive = N_eq[alive]
                                                                                                                                                                                                                                                                                                                             Je_pc = Je_alive / N_alive[:, None]
                                                                                                                                                                                                                                                                                                                                 off_pc = Je_pc.copy()
                                                                                                                                                                                                                                                                                                                                     np.fill_diagonal(off_pc, 0)
                                                                                                                                                                                                                                                                                                                                         gamma_net.append(np.mean(off_pc))

                                                                                                                                                                                                                                                                                                                                             np.random.seed(1000 + k)
                                                                                                                                                                                                                                                                                                                                                 dominant = alive[np.argmax(N_eq[alive])]
                                                                                                                                                                                                                                                                                                                                                     model_removed = make_model(delta_i, removed_idx=dominant)
                                                                                                                                                                                                                                                                                                                                                         y_pert = y_eq.copy()
                                                                                                                                                                                                                                                                                                                                                             noise = np.random.uniform(-0.05, 0.05, len(y_eq)) * np.abs(y_eq)
                                                                                                                                                                                                                                                                                                                                                                 y_pert = y_pert + noise
                                                                                                                                                                                                                                                                                                                                                                     y_pert[m:m + S] = np.maximum(y_pert[m:m + S], 0)
                                                                                                                                                                                                                                                                                                                                                                         y_pert[m + dominant] = 0.0
                                                                                                                                                                                                                                                                                                                                                                             y_eq_pert = integrate_to_eq(model_removed, y_pert)
                                                                                                                                                                                                                                                                                                                                                                                 N_pert = y_eq_pert[m:m + S]
                                                                                                                                                                                                                                                                                                                                                                                     N_sel = np.array([N_pert[i] if i in alive else 0.0 for i in range(S)])
                                                                                                                                                                                                                                                                                                                                                                                         l2 = np.linalg.norm(N_sel[alive] - N_eq[alive]) / (
                                                                                                                                                                                                                                                                                                                                                                                                 np.linalg.norm(N_eq[alive]) + 1e-10)
                                                                                                                                                                                                                                                                                                                                                                                                     dispersals.append(l2)

                                                                                                                                                                                                                                                                                                                                                                                                         print(f"delta={delta_mean:.3f}: gamma={gamma:.4f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                   f"dispersal(l2)={l2:.4f}, alive={len(alive)}", flush=True)

                                                                                                                                                                                                                                                                                                                                                                                                                   rho, p = spearmanr(Gammas, dispersals)
                                                                                                                                                                                                                                                                                                                                                                                                                   print(f"\nSpearman rho = {rho:.4f}, p = {p:.4f}")

                                                                                                                                                                                                                                                                                                                                                                                                                   fig, axes = plt.subplots(1, 3, figsize=(18, 5))

                                                                                                                                                                                                                                                                                                                                                                                                                   axes[0].scatter(Gammas, dispersals, s=100, color='steelblue',
                                                                                                                                                                                                                                                                                                                                                                                                                                   edgecolor='k', zorder=3)
                                                                                                                                                                                                                                                                                                                                                                                                                                   z = np.polyfit(Gammas, dispersals, 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                   x_fit = np.linspace(min(Gammas), max(Gammas), 50)
                                                                                                                                                                                                                                                                                                                                                                                                                                   axes[0].plot(x_fit, np.polyval(z, x_fit), 'r--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                label=f'rho = {rho:.3f}, p = {p:.4f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].set_xlabel(r'Effective coupling $\Gamma_{eff}$')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].set_ylabel('Dispersal (community response, L2)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].set_title('A. Coupling vs dispersal \n(positive correlation)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[0].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[1].plot(deltas_used, Gammas, 'ro-', linewidth=2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[1].set_xlabel(r'Mean mortality $\delta$ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[1].set_ylabel(r'$\Gamma_{eff}$')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[1].set_title('B. Effective coupling vs mortality \n(monotone decreasing)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                axes[2].plot(deltas_used, dispersals, 'gs-', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             label='Dispersal (L2)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[2].plot(deltas_used, Gammas, 'ro--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          label=r'$\Gamma_{eff}$')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[2].set_xlabel(r'Mean mortality $\delta$ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[2].set_ylabel('Magnitude')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[2].set_title('C. Both decline with mortality')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[2].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[2].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          plt.savefig('prediction5_final.png', dpi=150)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          plt.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("Plot saved: prediction5_final.png")