import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# ============================================================
# Prediction 4 (substantive optimization)
# Goal: provide direct evidence for the "high turnover,
# low standing stock" interpretation of the With-zoo group.
#
# New outputs:
# 1. Z dynamics (is zooplankton alive?)
# 2. R dynamics (is resource maintained?)
# 3. Flux / standing stock ratio (is turnover high?)
# 4. Effective species number exp(H) instead of raw Shannon
# ============================================================

S = 30
m = 3
q = 3
np.random.seed(42)

r = np.random.lognormal(np.log(0.7), 0.4, S)
delta_i = np.random.lognormal(np.log(0.25), 0.15, S)
K = np.random.lognormal(np.log(1.5), 0.4, (m, S))
V = np.random.lognormal(np.log(0.1), 0.2, (m, S))
mu = np.random.uniform(0.2, 0.4, (m, S))
S_input = np.array([0.05, 0.01, 0.003])
lambda_j = np.array([0.01, 0.01, 0.008])
alpha = 0.001
g_max = np.array([1.0, 0.8, 0.7])
K_Z = np.array([0.5, 0.6, 0.7])
m_k = np.array([0.1, 0.1, 0.12])


def model(t, y, graze_on):
    R = y[:m]
        N = y[m:m + S]
            Z = y[m + S:m + S + q]
                f = np.prod(R[:, None] / (K + R[:, None]), axis=0)
                    g = r * f
                        total_N = np.sum(N) + 1e-10
                            h = g_max[:, None] * N[None, :] / (K_Z[:, None] + total_N)
                                graze = h.T @ Z if graze_on else np.zeros(S)
                                    recycle = mu @ ((delta_i + graze) * N)
                                        dR = S_input + recycle - V @ (f * N) - lambda_j * R
                                            dN = N * (g - delta_i - graze) - alpha * N**2
                                                dZ = (Z * (0.7 * (h * N[None, :]).sum(axis=1) - m_k)
                                                          if graze_on else -m_k * Z)
                                                              return np.concatenate([dR, dN, dZ])


                                                              def shannon(N):
                                                                  p = N / (np.sum(N) + 1e-10)
                                                                      p = p[p > 1e-10]
                                                                          return -np.sum(p * np.log(p))


                                                                          T = 400
                                                                          t_eval = np.linspace(0, T, 400)

                                                                          y0_with = np.concatenate([np.array([5.0, 0.5, 0.3]),
                                                                                                    np.random.uniform(0.01, 0.5, S),
                                                                                                                              np.array([0.1, 0.1, 0.1])])
                                                                                                                              y0_without = np.concatenate([np.array([5.0, 0.5, 0.3]),
                                                                                                                                                           np.random.uniform(0.01, 0.5, S),
                                                                                                                                                                                        np.array([0.0, 0.0, 0.0])])

                                                                                                                                                                                        sol_with = solve_ivp(model, [0, T], y0_with, args=(True,),
                                                                                                                                                                                                             method='LSODA', rtol=1e-4, atol=1e-7,
                                                                                                                                                                                                                                  max_step=5.0, t_eval=t_eval)
                                                                                                                                                                                                                                  sol_without = solve_ivp(model, [0, T], y0_without, args=(False,),
                                                                                                                                                                                                                                                          method='LSODA', rtol=1e-4, atol=1e-7,
                                                                                                                                                                                                                                                                                  max_step=5.0, t_eval=t_eval)

                                                                                                                                                                                                                                                                                  H_with = np.array([shannon(sol_with.y[m:m + S, i])
                                                                                                                                                                                                                                                                                                     for i in range(len(sol_with.t))])
                                                                                                                                                                                                                                                                                                     H_without = np.array([shannon(sol_without.y[m:m + S, i])
                                                                                                                                                                                                                                                                                                                           for i in range(len(sol_without.t))])
                                                                                                                                                                                                                                                                                                                           Neff_with = np.exp(H_with)
                                                                                                                                                                                                                                                                                                                           Neff_without = np.exp(H_without)

                                                                                                                                                                                                                                                                                                                           total_N_with = np.sum(sol_with.y[m:m + S, :], axis=0)
                                                                                                                                                                                                                                                                                                                           total_N_without = np.sum(sol_without.y[m:m + S, :], axis=0)
                                                                                                                                                                                                                                                                                                                           total_Z_with = np.sum(sol_with.y[m + S:m + S + q, :], axis=0)
                                                                                                                                                                                                                                                                                                                           total_Z_without = np.sum(sol_without.y[m + S:m + S + q, :], axis=0)


                                                                                                                                                                                                                                                                                                                           # ============================================================
                                                                                                                                                                                                                                                                                                                           # Flux diagnostic at final state
                                                                                                                                                                                                                                                                                                                           # ============================================================
                                                                                                                                                                                                                                                                                                                           def flux_diag(sol, label):
                                                                                                                                                                                                                                                                                                                               R_eq = sol.y[:m, -1]
                                                                                                                                                                                                                                                                                                                                   N_eq = sol.y[m:m + S, -1]
                                                                                                                                                                                                                                                                                                                                       Z_eq = sol.y[m + S:m + S + q, -1]
                                                                                                                                                                                                                                                                                                                                           f_eq = np.prod(R_eq[:, None] / (K + R_eq[:, None]), axis=0)
                                                                                                                                                                                                                                                                                                                                               g_eq = r * f_eq
                                                                                                                                                                                                                                                                                                                                                   total_N = np.sum(N_eq) + 1e-10
                                                                                                                                                                                                                                                                                                                                                       h_eq = g_max[:, None] * N_eq[None, :] / (K_Z[:, None] + total_N)
                                                                                                                                                                                                                                                                                                                                                           graze = h_eq.T @ Z_eq
                                                                                                                                                                                                                                                                                                                                                               production = np.sum(g_eq * N_eq)
                                                                                                                                                                                                                                                                                                                                                                   loss = np.sum((delta_i + graze) * N_eq)
                                                                                                                                                                                                                                                                                                                                                                       standing = np.sum(N_eq) + 1e-12
                                                                                                                                                                                                                                                                                                                                                                           turnover = production / standing
                                                                                                                                                                                                                                                                                                                                                                               recycle_flux = np.sum(mu @ ((delta_i + graze) * N_eq))
                                                                                                                                                                                                                                                                                                                                                                                   cons_flux = np.sum(V @ (f_eq * N_eq))
                                                                                                                                                                                                                                                                                                                                                                                       print(f"\n{label}:")
                                                                                                                                                                                                                                                                                                                                                                                           print(f" Standing N = {standing:.6e}")
                                                                                                                                                                                                                                                                                                                                                                                               print(f" Standing Z = {np.sum(Z_eq):.6e}")
                                                                                                                                                                                                                                                                                                                                                                                                   print(f" Resource R = {R_eq}")
                                                                                                                                                                                                                                                                                                                                                                                                       print(f" Production flux = {production:.6e}")
                                                                                                                                                                                                                                                                                                                                                                                                           print(f" Loss flux = {loss:.6e}")
                                                                                                                                                                                                                                                                                                                                                                                                               print(f" Turnover = {turnover:.4f} d^-1")
                                                                                                                                                                                                                                                                                                                                                                                                                   print(f" Recycle/consume = {recycle_flux / (cons_flux + 1e-12):.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                       return turnover


                                                                                                                                                                                                                                                                                                                                                                                                                       turnover_with = flux_diag(sol_with, "With zooplankton")
                                                                                                                                                                                                                                                                                                                                                                                                                       turnover_without = flux_diag(sol_without, "Without zooplankton")


                                                                                                                                                                                                                                                                                                                                                                                                                       # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                       # 2x3 panel plot
                                                                                                                                                                                                                                                                                                                                                                                                                       # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                       fig, axes = plt.subplots(2, 3, figsize=(18, 10))

                                                                                                                                                                                                                                                                                                                                                                                                                       # Panel A: effective species number
                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].plot(sol_with.t, Neff_with, 'b-', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                       label='With zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].plot(sol_without.t, Neff_without, 'r--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       label='Without zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_xlabel('Time (d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_ylabel('Effective species number exp(H)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_title('A. Effective diversity')
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                       # Panel B: producer biomass (log scale to show magnitude)
                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 1].semilogy(sol_with.t, total_N_with + 1e-12, 'b-',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           linewidth=2, label='With zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[0, 1].semilogy(sol_without.t, total_N_without + 1e-12, 'r--',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               linewidth=2, label='Without zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 1].set_xlabel('Time (d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 1].set_ylabel('Total producer biomass (log scale)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 1].set_title('B. Producer standing stock')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 1].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # Panel C: zooplankton biomass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].plot(sol_with.t, total_Z_with, 'b-', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               label='With zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].plot(sol_without.t, total_Z_without, 'r--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               label='Without zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].set_xlabel('Time (d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].set_ylabel('Total zooplankton biomass')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].set_title('C. Zooplankton standing stock')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               axes[0, 2].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # Panel D: resource dynamics (log scale)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               for j in range(m):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   axes[1, 0].semilogy(sol_with.t, R_with := sol_with.y[j, :],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '-', linewidth=1.5, alpha=0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   label=f'R{j+1} with')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].semilogy(sol_without.t, sol_without.y[j, :],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               '--', linewidth=1.5, alpha=0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       label=f'R{j+1} without')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].set_xlabel('Time (d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].set_ylabel('Resource concentration (log scale)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].set_title('D. Resource dynamics')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].legend(fontsize=6, ncol=2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 0].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # Panel E: turnover rate over time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # Compute instantaneous turnover
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       turnover_with_t = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       turnover_without_t = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       for i in range(len(sol_with.t)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           R_i = sol_with.y[:m, i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               N_i = sol_with.y[m:m + S, i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f_i = np.prod(R_i[:, None] / (K + R_i[:, None]), axis=0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       prod_i = np.sum(r * f_i * N_i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           stand_i = np.sum(N_i) + 1e-12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               turnover_with_t.append(prod_i / stand_i)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   R_i = sol_without.y[:m, i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       N_i = sol_without.y[m:m + S, i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f_i = np.prod(R_i[:, None] / (K + R_i[:, None]), axis=0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               prod_i = np.sum(r * f_i * N_i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   stand_i = np.sum(N_i) + 1e-12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       turnover_without_t.append(prod_i / stand_i)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].plot(sol_with.t, turnover_with_t, 'b-', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       label='With zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].plot(sol_without.t, turnover_without_t, 'r--', linewidth=2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       label='Without zooplankton')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].set_xlabel('Time (d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].set_ylabel('Turnover rate (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].set_title('E. Community turnover rate')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].legend()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # Panel F: annotation box with flux diagnostics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[1, 2].axis('off')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f"Final-state diagnostics\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f"{'='*35}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f"With zooplankton:\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       f" Standing N = {total_N_with[-1]:.3e}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f" Standing Z = {total_Z_with[-1]:.3e}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f" Turnover = {turnover_with_t[-1]:.3f} /d\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f" exp(H) = {Neff_with[-1]:.3f}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       f"\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f"Without zooplankton:\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f" Standing N = {total_N_without[-1]:.3e}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f" Standing Z = {total_Z_without[-1]:.3e}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       f" Turnover = {turnover_without_t[-1]:.3f} /d\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f" exp(H) = {Neff_without[-1]:.3f}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f"\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f"Interpretation:\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       f"With-zoo group has LOW standing stock\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           f"but HIGH turnover -> rapid cycling.\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f"Without-zoo group has HIGH standing stock\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f"but LOW turnover -> accumulation."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   axes[1, 2].text(0.0, 0.5, text, fontsize=9, verticalalignment='center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontfamily='monospace',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   bbox=dict(boxstyle='round', facecolor='lightyellow',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             alpha=0.8))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             plt.savefig('prediction4_optimized.png', dpi=150)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             plt.close()