import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import sys

out_file = open('ecosystem_C_result.txt', 'w')
def log(msg):
    out_file.write(msg + '\n')
        out_file.flush()

        log("Script started: Route C (compressed recycling)")

        S = 30
        m = 3
        np.random.seed(42)
        n_repeat = 5

        r = np.random.lognormal(np.log(0.7), 0.4, S)
        K = np.random.lognormal(np.log(1.5), 0.4, (m, S))
        V = np.random.lognormal(np.log(0.1), 0.2, (m, S)) * 0.66
        alpha = 0.001

        r_min, r_max = r.min(), r.max()
        mu_r = 0.05 + 0.75 * (r - r_min) / (r_max - r_min)
        mu = np.tile(mu_r * 0.6, (m, 1))

        S_input = np.array([0.05, 0.01, 0.003])
        lambda_j = np.array([0.0001, 0.0001, 0.00008])

        mu_N = mu.mean()
        V_N = V.mean()
        r_mean = r.mean()
        f_val = 0.5
        delta_inst = V_N * f_val / mu_N
        delta_growth = r_mean * f_val

        log(f"Params:")
        log(f" mu mean={mu_N:.4f} (range [{mu.min():.3f},{mu.max():.3f}])")
        log(f" V mean={V_N:.4f} (×0.66 scaled)")
        log(f" lambda = {lambda_j}")
        log(f" delta_inst={delta_inst:.4f}, delta_growth={delta_growth:.4f}")
        log(f" V×0.66: J_eff transition aligned with delta_growth")

        def model_factory(delta_vec, removed_idx=None):
            def model(t, y):
                    R = y[:m]
                            N = y[m:m + S].copy()
                                    if removed_idx is not None:
                                                N[removed_idx] = 0.0
                                                        f = np.prod(R[:, None] / (K + R[:, None]), axis=0)
                                                                g = r * f
                                                                        recycle = mu @ (delta_vec * N)
                                                                                dR = S_input + recycle - V @ (f * N) - lambda_j * R
                                                                                        dN = N * (g - delta_vec) - alpha * N**2
                                                                                                if removed_idx is not None:
                                                                                                            dN[removed_idx] = 0.0
                                                                                                                    return np.concatenate([dR, dN])
                                                                                                                        return model

                                                                                                                        def integrate_to_eq(model, y0, T=600):
                                                                                                                            sol = solve_ivp(model, [0, T], y0, method='BDF', rtol=1e-8, atol=1e-12,
                                                                                                                                                max_step=5.0, max_num_steps=50000)
                                                                                                                                                    return sol.y[:, -1]

                                                                                                                                                    def numerical_jacobian(model, y, eps=1e-4):
                                                                                                                                                        n = len(y)
                                                                                                                                                            J = np.zeros((n, n))
                                                                                                                                                                F0 = model(0, y)
                                                                                                                                                                    for i in range(n):
                                                                                                                                                                            yp = y.copy()
                                                                                                                                                                                    yp[i] += eps
                                                                                                                                                                                            J[:, i] = (model(0, yp) - F0) / eps
                                                                                                                                                                                                return J

                                                                                                                                                                                                def analyze_run(delta_vec):
                                                                                                                                                                                                    model = model_factory(delta_vec)
                                                                                                                                                                                                        y0 = np.concatenate([np.array([5.0, 0.5, 0.3]), np.random.uniform(0.01, 0.5, S)])
                                                                                                                                                                                                            y_eq = integrate_to_eq(model, y0)
                                                                                                                                                                                                                R_eq = y_eq[:m]
                                                                                                                                                                                                                    N_eq = y_eq[m:m + S]
                                                                                                                                                                                                                        alive = np.where(N_eq > 1e-4)[0]
                                                                                                                                                                                                                            S_star = len(alive)

                                                                                                                                                                                                                                if S_star == 0:
                                                                                                                                                                                                                                        return 0.0, 0.0, np.nan, np.nan

                                                                                                                                                                                                                                            f_eq = np.prod(R_eq[:, None] / (K + R_eq[:, None]), axis=0)
                                                                                                                                                                                                                                                recycle_flux = mu @ (delta_vec * N_eq)
                                                                                                                                                                                                                                                    consumption_flux = V @ (f_eq * N_eq)
                                                                                                                                                                                                                                                        ratio_per_res = np.where(consumption_flux > 1e-10,
                                                                                                                                                                                                                                                                                     recycle_flux / (consumption_flux + 1e-12), np.nan)
                                                                                                                                                                                                                                                                                         recycle_ratio = np.nanmean(ratio_per_res)

                                                                                                                                                                                                                                                                                             if S_star >= 3:
                                                                                                                                                                                                                                                                                                     J = numerical_jacobian(model, y_eq)
                                                                                                                                                                                                                                                                                                             J_RR = J[:m, :m]
                                                                                                                                                                                                                                                                                                                     J_RN = J[:m, m:]
                                                                                                                                                                                                                                                                                                                             J_NR = J[m:, :m]
                                                                                                                                                                                                                                                                                                                                     J_NN = J[m:m + S, m:m + S]
                                                                                                                                                                                                                                                                                                                                             J_eff_NN = J_NN - J_NR @ np.linalg.solve(J_RR, J_RN)
                                                                                                                                                                                                                                                                                                                                                     N_alive = N_eq[alive]
                                                                                                                                                                                                                                                                                                                                                             J_eff_alive = J_eff_NN[np.ix_(alive, alive)] / N_alive[:, None]
                                                                                                                                                                                                                                                                                                                                                                     off = J_eff_alive.copy()
                                                                                                                                                                                                                                                                                                                                                                             np.fill_diagonal(off, 0)
                                                                                                                                                                                                                                                                                                                                                                                     off_flat = off.flatten()
                                                                                                                                                                                                                                                                                                                                                                                             off_diag_sign = np.mean(off_flat) if len(off_flat) > 0 else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                 else:
                                                                                                                                                                                                                                                                                                                                                                                                         off_diag_sign = np.nan

                                                                                                                                                                                                                                                                                                                                                                                                             if S_star >= 5:
                                                                                                                                                                                                                                                                                                                                                                                                                     rare_idx = alive[np.argmin(N_eq[alive])]
                                                                                                                                                                                                                                                                                                                                                                                                                             model_removed = model_factory(delta_vec, removed_idx=rare_idx)
                                                                                                                                                                                                                                                                                                                                                                                                                                     y_eq_removed = integrate_to_eq(model_removed, y_eq)
                                                                                                                                                                                                                                                                                                                                                                                                                                             R_rem = y_eq_removed[:m]
                                                                                                                                                                                                                                                                                                                                                                                                                                                     f_rem = np.prod(R_rem[:, None] / (K + R_rem[:, None]), axis=0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                             g_rem = r[rare_idx] * f_rem[rare_idx]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     invasion_growth = g_rem - delta_vec[rare_idx]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 invasion_growth = np.nan

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return S_star, recycle_ratio, off_diag_sign, invasion_growth

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     log("Starting main loop...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     delta_values = np.linspace(0.05, 0.55, 15)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     results = {k: [] for k in ['S_star', 'recycle_ratio', 'off_diag_sign', 'invasion_growth']}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     results_std = {k: [] for k in results}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     for i, delta_mean in enumerate(delta_values):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         runs = {k: [] for k in results}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for rep in range(n_repeat):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     delta_vec = np.random.lognormal(np.log(delta_mean), 0.15, S)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             result = analyze_run(delta_vec)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     S_star, rr, ods, ig = result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             runs['S_star'].append(S_star)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     runs['recycle_ratio'].append(rr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             runs['off_diag_sign'].append(ods)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     runs['invasion_growth'].append(ig)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for k in results:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 vals = [v for v in runs[k] if not np.isnan(v)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         results[k].append(np.mean(vals) if vals else np.nan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 results_std[k].append(np.std(vals) if vals else np.nan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     log(f"delta={delta_mean:.3f} [{i+1}/15]: S*={results['S_star'][-1]:.1f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             f"recycle_ratio={results['recycle_ratio'][-1]:.3f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     f"J_eff={results['off_diag_sign'][-1]:+.8f}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             f"invasion={results['invasion_growth'][-1]:+.4f}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             log("Main loop done, creating plot...")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             fig, axes = plt.subplots(2, 2, figsize=(13, 9))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             axes[0, 0].errorbar(delta_values, results['S_star'], yerr=results_std['S_star'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fmt='bo-', linewidth=2, capsize=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 0].axvline(delta_inst, color='b', linestyle='--',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label=f'Instantaneous: {delta_inst:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    axes[0, 0].axvline(delta_growth, color='r', linestyle=':',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       label=f'Growth bound: {delta_growth:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_xlabel('Mean mortality δ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_ylabel('Surviving species S*')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].set_title('A. S* (not criterion-sensitive)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].legend(fontsize=8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 0].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       axes[0, 1].errorbar(delta_values, results['recycle_ratio'], yerr=results_std['recycle_ratio'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fmt='go-', linewidth=2, capsize=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[0, 1].axhline(1.0, color='k', linestyle='-', linewidth=1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label='Recycle = consumption')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[0, 1].axvline(delta_inst, color='b', linestyle='--',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 label=f'Per-species criterion: {delta_inst:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 1].set_xlabel('Mean mortality δ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 1].set_ylabel('Recycle / consumption flux')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 1].set_title('B. Community-level criterion')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 1].legend(fontsize=8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[0, 1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 axes[1, 0].errorbar(delta_values, results['off_diag_sign'], yerr=results_std['off_diag_sign'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     fmt='mo-', linewidth=2, capsize=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     axes[1, 0].axhline(0.0, color='k', linestyle='-', linewidth=1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label='Competition ↔ Facilitation')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        axes[1, 0].axvline(delta_inst, color='b', linestyle='--',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           label=f'Instantaneous: {delta_inst:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 0].axvline(delta_growth, color='r', linestyle=':',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label=f'Growth bound: {delta_growth:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].set_xlabel('Mean mortality δ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].set_ylabel('Mean J_eff off-diagonal (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].set_title('C. Effective interaction (J_eff) — transition at δ_growth')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].legend(fontsize=8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].grid(True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 0].ticklabel_format(style='sci', axis='y', scilimits=(-4,-4))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              axes[1, 1].errorbar(delta_values, results['invasion_growth'], yerr=results_std['invasion_growth'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fmt='ro-', linewidth=2, capsize=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  axes[1, 1].axhline(0.0, color='k', linestyle='-', linewidth=1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     label='Invasion succeeds ↔ fails')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     axes[1, 1].axvline(delta_inst, color='b', linestyle='--',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label=f'Instantaneous: {delta_inst:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        axes[1, 1].axvline(delta_growth, color='r', linestyle=':',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           label=f'Growth bound: {delta_growth:.3f}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 1].set_xlabel('Mean mortality δ (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 1].set_ylabel('Invasion growth rate (1/d)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 1].set_title('D. Rare-species invasion')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 1].legend(fontsize=8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           axes[1, 1].grid(True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           plt.savefig('prediction1_C.png', dpi=150)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           plt.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log("Plot saved!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log("\n" + "=" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log("Route C summary (compressed recycling + V×0.66)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log("=" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"Instantaneous criterion threshold: δ* = {delta_inst:.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"Growth bound: δ_max = {delta_growth:.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"mu-r correlation: mu in [{mu.min():.3f}, {mu.max():.3f}], mean={mu_N:.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"lambda loss rate: {lambda_j[0]:.5f} (was 0.01)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"V consumption: mean={V_N:.4f} (×0.66 scale)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"J_eff transition aligned with δ_growth = {delta_growth:.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log(f"Ideal: J_eff negative at low δ (competition), positive at high δ (facilitation)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           log("ALL DONE!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           out_file.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           print("Script completed successfully!")